# This showcases the changes added so far:
# - We can use llama models (just write the hugginface repo name in base_model_name and it downloads automatically)
# - We can set mask model temperature
# - We can set generator model temp
# - If we perform the pre-perturbation experiments (which perturbs the examples generated by the LLM before classifying them) we can set the temp of the pre-perturbation model

python run.py --output_name main --base_model_name meta-llama/Llama-3.2-3B --mask_filling_model_name t5-base --n_perturbation_list 10 --n_samples 100 --pct_words_masked 0.3 --span_length 2 --mask_temperature 2 --generator_temperature 2 --pre_perturb_temperature 1.5 --pre_perturb_pct 0.2 --cache_dir ./cache
