# Tersoo
python run.py --cache_dir /scratch/gpfs/tu8435/model_cache --output_name scale --base_model_name gpt2-xl --mask_filling_model_name t5-small --n_perturbation_list 5,25 --n_samples 200 --pct_words_masked 0.3 --span_length 2 --dataset squad --dataset_key context --random_fills --random_fills_tokens
python run.py --cache_dir /scratch/gpfs/tu8435/model_cache --output_name scale --base_model_name gpt2-xl --mask_filling_model_name t5-small --n_perturbation_list 5,25 --n_samples 200 --pct_words_masked 0.3 --span_length 2 --dataset squad --dataset_key context
python run.py --cache_dir /scratch/gpfs/tu8435/model_cache --output_name scale --base_model_name gpt2-xl --mask_filling_model_name t5-base --n_perturbation_list 5,25 --n_samples 200 --pct_words_masked 0.3 --span_length 2 --dataset squad --dataset_key context
python run.py --cache_dir /scratch/gpfs/tu8435/model_cache --output_name scale --base_model_name gpt2-xl --mask_filling_model_name t5-large --n_perturbation_list 5,25 --n_samples 200 --pct_words_masked 0.3 --span_length 2 --dataset squad --dataset_key context
python run.py --cache_dir /scratch/gpfs/tu8435/model_cache --output_name scale --base_model_name gpt2-xl --mask_filling_model_name t5-3b --n_perturbation_list 5,25 --n_samples 200 --pct_words_masked 0.3 --span_length 2 --dataset squad --dataset_key context

python run.py --cache_dir /scratch/gpfs/tu8435/model_cache --output_name scale --base_model_name gpt2-large --mask_filling_model_name t5-small --n_perturbation_list 5,25 --n_samples 200 --pct_words_masked 0.3 --span_length 2 --dataset squad --dataset_key context --random_fills --random_fills_tokens
python run.py --cache_dir /scratch/gpfs/tu8435/model_cache --output_name scale --base_model_name gpt2-large --mask_filling_model_name t5-small --n_perturbation_list 5,25 --n_samples 200 --pct_words_masked 0.3 --span_length 2 --dataset squad --dataset_key context
python run.py --cache_dir /scratch/gpfs/tu8435/model_cache --output_name scale --base_model_name gpt2-large --mask_filling_model_name t5-base --n_perturbation_list 5,25 --n_samples 200 --pct_words_masked 0.3 --span_length 2 --dataset squad --dataset_key context
python run.py --cache_dir /scratch/gpfs/tu8435/model_cache --output_name scale --base_model_name gpt2-large --mask_filling_model_name t5-large --n_perturbation_list 5,25 --n_samples 200 --pct_words_masked 0.3 --span_length 2 --dataset squad --dataset_key context
python run.py --cache_dir /scratch/gpfs/tu8435/model_cache --output_name scale --base_model_name gpt2-large --mask_filling_model_name t5-3b --n_perturbation_list 5,25 --n_samples 200 --pct_words_masked 0.3 --span_length 2 --dataset squad --dataset_key context

python run.py --cache_dir /scratch/gpfs/tu8435/model_cache --output_name scale --base_model_name gpt2-medium --mask_filling_model_name t5-small --n_perturbation_list 5,25 --n_samples 200 --pct_words_masked 0.3 --span_length 2 --dataset squad --dataset_key context --random_fills --random_fills_tokens
python run.py --cache_dir /scratch/gpfs/tu8435/model_cache --output_name scale --base_model_name gpt2-medium --mask_filling_model_name t5-small --n_perturbation_list 5,25 --n_samples 200 --pct_words_masked 0.3 --span_length 2 --dataset squad --dataset_key context
python run.py --cache_dir /scratch/gpfs/tu8435/model_cache --output_name scale --base_model_name gpt2-medium --mask_filling_model_name t5-base --n_perturbation_list 5,25 --n_samples 200 --pct_words_masked 0.3 --span_length 2 --dataset squad --dataset_key context
python run.py --cache_dir /scratch/gpfs/tu8435/model_cache --output_name scale --base_model_name gpt2-medium --mask_filling_model_name t5-large --n_perturbation_list 5,25 --n_samples 200 --pct_words_masked 0.3 --span_length 2 --dataset squad --dataset_key context
python run.py --cache_dir /scratch/gpfs/tu8435/model_cache --output_name scale --base_model_name gpt2-medium --mask_filling_model_name t5-3b --n_perturbation_list 5,25 --n_samples 200 --pct_words_masked 0.3 --span_length 2 --dataset squad --dataset_key context

python run.py --cache_dir /scratch/gpfs/tu8435/model_cache --output_name scale --base_model_name gpt2 --mask_filling_model_name t5-small --n_perturbation_list 5,25 --n_samples 200 --pct_words_masked 0.3 --span_length 2 --dataset squad --dataset_key context --random_fills --random_fills_tokens
python run.py --cache_dir /scratch/gpfs/tu8435/model_cache --output_name scale --base_model_name gpt2 --mask_filling_model_name t5-small --n_perturbation_list 5,25 --n_samples 200 --pct_words_masked 0.3 --span_length 2 --dataset squad --dataset_key context
python run.py --cache_dir /scratch/gpfs/tu8435/model_cache --output_name scale --base_model_name gpt2 --mask_filling_model_name t5-base --n_perturbation_list 5,25 --n_samples 200 --pct_words_masked 0.3 --span_length 2 --dataset squad --dataset_key context
python run.py --cache_dir /scratch/gpfs/tu8435/model_cache --output_name scale --base_model_name gpt2 --mask_filling_model_name t5-large --n_perturbation_list 5,25 --n_samples 200 --pct_words_masked 0.3 --span_length 2 --dataset squad --dataset_key context
python run.py --cache_dir /scratch/gpfs/tu8435/model_cache --output_name scale --base_model_name gpt2 --mask_filling_model_name t5-3b --n_perturbation_list 5,25 --n_samples 200 --pct_words_masked 0.3 --span_length 2 --dataset squad --dataset_key context